# Generated by Django 5.2.2 on 2025-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, help_text='Рабочийдің қызмет көрсету ауданы', max_length=100, null=True),
        ),
    ]
