# Generated by Django 5.2.2 on 2025-06-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_service_type_profile_district'),
        ('orders', '0002_district_order_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.servicetype'),
        ),
    ]
