# Generated by Django 5.2.2 on 2025-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Заказчик'), ('worker', 'Рабочий'), ('admin', 'Админ')], max_length=50),
        ),
    ]
