# Generated by Django 5.2.2 on 2025-06-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
