# Generated by Django 5.2.2 on 2025-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, choices=[('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Шымкент', 'Шымкент')], help_text='Рабочийдің қызмет көрсету ауданы', max_length=100, null=True),
        ),
    ]
