# Generated by Django 5.2.2 on 2025-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, choices=[('almalinsky', 'Алмалинский район'), ('alatau', 'Алатауский район'), ('auezov', 'Ауэзовский район'), ('bostandyk', 'Бостандыкский район'), ('zhetysu', 'Жетысуский район'), ('medeu', 'Медеуский район'), ('nauryzbay', 'Наурызбайский район'), ('turksib', 'Турксибский район')], help_text='Рабочийдің қызмет көрсету ауданы', max_length=100, null=True),
        ),
    ]
