# Generated by Django 5.2.3 on 2025-06-20 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, choices=[('almalinsky', 'Алмалинский район'), ('alatau', 'Алатауский район'), ('auezov', 'Ауэзовский район'), ('bostandyk', 'Бостандыкский район'), ('zhetysu', 'Жетысуский район'), ('medeu', 'Медеуский район'), ('nauryzbay', 'Наурызбайский район'), ('turksib', 'Турксибский район')], max_length=100, null=True, verbose_name='Район')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('accepted', 'Принят'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылган уақыты')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ұзындық')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ені')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мекен-жай')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бағасы')),
                ('desired_time', models.DateTimeField(blank=True, null=True, verbose_name='Қалаған уақыт')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон нөмірі')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_orders', to=settings.AUTH_USER_MODEL, verbose_name='Жұмысшы')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.servicetype', verbose_name='Қызмет түрі')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
    ]
