# Generated by Django 5.2.2 on 2025-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_district_order_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('accepted', 'Принят'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='new', max_length=20),
        ),
    ]
