# Generated by Django 5.2.2 on 2025-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_district_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Шымкент', 'Шымкент')], max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңартылган уақыты'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
