# Generated by Django 5.2.2 on 2025-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_district_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('almalinsky', 'Алмалинский район'), ('alatau', 'Алатауский район'), ('auezov', 'Ауэзовский район'), ('bostandyk', 'Бостандыкский район'), ('zhetysu', 'Жетысуский район'), ('medeu', 'Медеуский район'), ('nauryzbay', 'Наурызбайский район'), ('turksib', 'Турксибский район')], max_length=100, null=True, verbose_name='Район'),
        ),
    ]
