# Generated by Django 5.2.3 on 2025-06-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('start_date', models.DateTimeField(verbose_name='Басталу уақыты')),
                ('end_date', models.DateTimeField(verbose_name='Аяқталу уақыты')),
                ('prize', models.CharField(max_length=200, verbose_name='Сыйлық')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурстар',
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.TextField(verbose_name='Жұмыс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыты')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contests.contest', verbose_name='Конкурс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL, verbose_name='Қатысушы')),
            ],
            options={
                'verbose_name': 'Конкурсқа қатысу',
                'verbose_name_plural': 'Конкурсқа қатысулар',
            },
        ),
    ]
