# Generated by Django 5.2.3 on 2025-06-22 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('status', models.CharField(choices=[('new', 'Жаңа'), ('in_progress', 'Өңделуде'), ('closed', 'Жабылған')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Төмен'), ('medium', 'Орташа'), ('high', 'Жоғары')], default='medium', max_length=20, verbose_name='Басымдық')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыт')),
                ('file', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Файл')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.servicetype', verbose_name='Қызмет түрі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Тікет',
                'verbose_name_plural': 'Тікеттер',
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('file', models.FileField(blank=True, null=True, upload_to='ticket_responses/', verbose_name='Файл')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='helpdesk.ticket', verbose_name='Тікет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_responses', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тікет жауабы',
                'verbose_name_plural': 'Тікет жауаптары',
            },
        ),
    ]
