# Generated by Django 5.2.3 on 2025-06-20 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Форум жазбасы',
                'verbose_name_plural': 'Форум жазбалары',
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Пікір мазмұны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost', verbose_name='Жазба')),
            ],
            options={
                'verbose_name': 'Форум пікірі',
                'verbose_name_plural': 'Форум пікірлері',
            },
        ),
    ]
