# Generated by Django 5.2.3 on 2025-06-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сұрау')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('responded', models.BooleanField(default=False, verbose_name='Жауап берілді')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Субсидия сұрауы',
                'verbose_name_plural': 'Субсидия сұраулары',
            },
        ),
    ]
